# Generated by Django 5.0.3 on 2024-04-27 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='char_field',
            field=models.CharField(default='se', max_length=30),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='date_time_field',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
